name: CI - Windows
on: [pull_request, push]

jobs:
  win-build:
    runs-on: windows-latest

    matrix:
      include:
        - { icon: '⬛', qt_version: 5}
        - { icon: '🟦', qt_version: 6}
    name: 🚧${{ matrix.icon }} Qt${{ matrix.sys }} | build

    strategy:
      fail-fast: false
      matrix:
        qt_version: ["5", "6"]

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: '🧰 Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 'setup msys2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-qt${{ matrix.qt_version }}-static
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-openssl
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-libtorrent-rasterbar

    - name: '🚧 Build package'
      run: |
        cmake \
          -B build \
          -G "Ninja" \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DQT${{ matrix.qt_version }}=ON \
          -DVERBOSE_CONFIGURE=ON \
          --graphviz=build/target_graph.dot
        cmake --build build

    - name: '📤 upload package'
      uses: actions/upload-artifact@v2
      with:
        name: qBittorrent-CI_Windows-x64_Qt-${{ matrix.qt_version }}
        path: |
          build/compile_commands.json
          build/install_manifest.txt
          build/target_graph.dot
          build/qbittorrent.exe
          libtorrent/cmake-build-dir/compile_commands.json
          libtorrent/cmake-build-dir/target_graph.dot
