name: CI - Windows
on: [pull_request, push]

jobs:

  win-build:
    runs-on: windows-latest

    name: 🚧${{ matrix.icon }} Qt5 | build

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: 'setup msys2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >
          mingw-w64-x86_64-qt5-static
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-openssl
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-libtorrent-rasterbar
          mingw-w64-x86_64-python

    - name: '🚧 Build package'
      run: |
        cmake \
          -B build \
          -G "Ninja" \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DQT5=ON \
          -DVERBOSE_CONFIGURE=ON \
          --graphviz=build/target_graph.dot
        cmake --build build
        mkdir build/upload/
        cp build/qbittorrent.exe build/upload/
        python ldd-check/ldd-check.py -cp build/upload/qbittorrent.exe

    - name: '📤 upload package'
      uses: actions/upload-artifact@v2
      with:
        name: qBittorrent-CI_Windows-x64_Qt5
        path: build/upload/
